sudo: required

language: go

services:  
    - docker

env:  
    global:
        - DOCKER_VERSION=1.10.1-0~trusty

before_install:  
    # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

script:  
    - docker version
    - ls -R /etc
