resources:
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '5 5 * * *'     # every day
 
pipelines:     
  - name: pipeline_scheduled_triggers
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: cron_trigger
        execution:
          onExecute:
            - printenv
